# Generated by Django 4.2.13 on 2025-05-13 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_category_is_published_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="location",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="created_at",
        ),
    ]
