# Generated by Django 4.2.13 on 2025-05-13 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_remove_category_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 5, 13, 14, 19, 4, 704144, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Добавлено",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 5, 13, 14, 19, 11, 262455, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Добавлено",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default="2024-01-01T00:00:00Z",
                verbose_name="Добавлено",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="Идентификатор страницы для URL; разрешены символы        латиницы, цифры, дефис и подчёркивание.",
                unique=True,
                verbose_name="Идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(
                help_text="Если установить дату и время в будущем — можно        делать отложенные публикации.",
                verbose_name="Дата и время публикации",
            ),
        ),
    ]
